[build]
  publish = "public"
  command = "npm run build"

[dev]
  command = "npm run start"
  port = 3000

 
  [[redirects]]
from = "https://test11bd.netlify.app/*"
to = "https://test11bd.netlify.app/:splat"
status = 200
force = true
